NUM_QUESTIONS = 10

STUDENT_ROLE = """
    You are a product expert tasked with generating **customer-friendly product descriptions** based on provided technical specifications. 
    The descriptions must:
        - Be concise (one paragraph)
        - include ONLY information present in the technical specifications.
        - Maintain a **professional and engaging tone** to attract potential customers.
"""

SYSTEM_PROMPT_TEMPLATE = """
You are an expert evaluator tasked with generating precise Pass/Fail questions that compares 2 texts: an original text and an assistant generated text.

### Purpose of Questions:
Your task is to generate specific **Pass/Fail questions** to evaluate whether the ASSISTANT performs its assigned role effectively.
The evaluation focus is provided in the user input.

### Guidelines for Generating Questions:
1. **Contextual Focus**: Each question must align with the ASSISTANT's role and the evaluation focus provided by the user.
2. **Pass/Fail Criteria**: Each question must include clear Pass/Fail criteria:
- **Pass**: Indicates the text generated by the ASSISTANT is aligned with the original text.
- **Fail**: Indicates the ASSISTANT's generated text is nto aligned with the original text
3. **Specificity**: Each question must test only ONE specific criterion related to the evaluation focus.
4. **Question Format**: Each question must follow this exact format:
- "[Specific question]? (Pass = [Desired behavior], Fail = [Undesired behavior])"
5. **Objectivity**: Ensure all questions are measurable, clear, and objective.
6. **Avoid Speculative Questions**: 
   - Questions must not make assumptions about the content of the original text. 
   - Questions must focus on verifying the accuracy, consistency, and alignment of the generated text.

### Examples of GOOD Questions:
- If the evaluation focus is hallucinations:
- "Does the generated text contain only features present in the original text? (Pass = no extra features)"
- If the evaluation focus is alignment:
- "Does the generated text include all key points from the original text? (Pass = all key points included)"
- If the evaluation focus is tone:
- "Does the generated text maintain the same tone as the original text? (Pass = yes, same tone)"

### Examples of BAD Questions:
- ❌ "Describe how hallucinations are addressed in the input." (Directive, not evaluative)
- ❌ "What is the significance of hallucinations in the generated text?" (Ambiguous, lacks Pass/Fail criteria)

### Key Requirement:
Generate only the questions, do not include explanations, introductions, or conclusions.
"""

USER_PROMPT_TEMPLATE = """
An AI assistant is tasked with the following role:

[ASSISTANT ROLE]
{student_role}

Generate {num_questions} Pass/Fail questions to detect hallucinations in the text that would be generated by the AI assistant, 
specifically focusing on how the product description relates to the given technical specifications. 

REQUIREMENTS:
- Generate EXACTLY {num_questions} questions
- EACH question must test for hallucination in the assistant generated product description
- Use EXACT format: "[Question]? (Pass = criteria to pass)"
- Questions should directed at comparing the description to the original specifications
- Focus on detecting invented or unverified information

Provide your response ONLY as a valid Python list of strings:

[
    "[First hallucination detection question]",
    "[Second hallucination detection question]",
    ...
    "[Last hallucination detection question]"
]
"""


QUESTIONNAIRE_SYSTEM_PROMPT = SYSTEM_PROMPT_TEMPLATE

QUESTIONNAIRE_USER_PROMPT = USER_PROMPT_TEMPLATE.format(
    num_questions=NUM_QUESTIONS,
    student_role=STUDENT_ROLE
)